### ISSUE TITLE
無法使用

### ISSUE THREAD

**Issue by JacobLinCool** [Peugin/BaHaLuckyDraw#2]
使用如下參數無法正常使用
![image](https://user-images.githubusercontent.com/28478594/130352620-d323a9b9-2fb5-4ae7-8851-857d04f73432.png)

巴哈文章網址：https://forum.gamer.com.tw/C.php?bsn=60076&snA=6515182

錯誤訊息：
![image](https://user-images.githubusercontent.com/28478594/130352654-498e7d7a-8195-40ff-8e79-ac783d990664.png)

**Comment by Peugin** [comment]
很抱歉這麼晚才回應，目前功能已修復正常。
